gdax_ltc_btc:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh backfill gdax.LTC-BTC; ./zenbot.sh sim gdax.LTC-BTC --buy_pct 24 --sell_pct 24; ./zenbot.sh trade gdax.LTC-BTC --buy_pct 24 --sell_pct 24
  restart: always

gdax_ltc_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh backfill gdax.LTC-EUR; ./zenbot.sh sim gdax.LTC-EUR --buy_pct 24 --sell_pct 24; ./zenbot.sh trade gdax.LTC-EUR --buy_pct 24 --sell_pct 24
  restart: always

gdax_eth_btc:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh backfill gdax.ETH-BTC; ./zenbot.sh sim gdax.ETH-BTC --buy_pct 24 --sell_pct 24; ./zenbot.sh trade gdax.ETH-BTC --buy_pct 24 --sell_pct 24
  restart: always

gdax_eth_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh backfill gdax.ETH-EUR; ./zenbot.sh sim gdax.ETH-EUR --buy_pct 24 --sell_pct 24; ./zenbot.sh trade gdax.ETH-EUR --buy_pct 24 --sell_pct 24
  restart: always

gdax_btc_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh backfill gdax.BTC-EUR;./zenbot.sh sim gdax.BTC-EUR --buy_pct 24 --sell_pct 24; ./zenbot.sh trade gdax.BTC-EUR --buy_pct 24 --sell_pct 24
  restart: always

mongodb:
  image: mongo:latest
  volumes_from:
    - mongodb-data
  command: mongod --smallfiles
  restart: always

mongodb-data:
  image: mongo:latest
  volumes:
    - ./data/db:/data/db
  command: "true"
