gdax_ltc_btc:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade --conf ./conf.ltc_btc.js
  restart: always

gdax_ltc_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: /bin/true ; ./zenbot.sh trade --conf ./conf.ltc_eur.js

gdax_eth_btc:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: /bin/true ; echo "./zenbot.sh trade --conf ./conf.eth_btc.js"

gdax_eth_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade --conf ./conf.eth_eur.js
  restart: always

mongodb:
  image: mongo:latest
  volumes_from:
    - mongodb-data
  command: mongod --smallfiles
  restart: always

mongodb-data:
  image: mongo:latest
  volumes:
    - ./data/db:/data/db
  command: "true"
