gdax_ltc_btc:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade gdax.LTC-BTC
  restart: always

gdax_ltc_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade gdax.LTC-EUR
  restart: always

gdax_eth_btc:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade gdax.ETH-BTC
  restart: always

gdax_eth_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade gdax.ETH-EUR
  restart: always

gdax_btc_eur:
  build: .
  tty: true
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade gdax.BTC-EUR
  restart: always

mongodb:
  image: mongo:latest
  volumes_from:
    - mongodb-data
  command: mongod --smallfiles
  restart: always

mongodb-data:
  image: mongo:latest
  volumes:
    - ./data/db:/data/db
  command: "true"
